name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types:
      - published

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Package
        run: dotnet pack --configuration Release --no-restore
      - name: Push to GitHub Packages
        run: dotnet nuget push "Techgamr.Utils.General/bin/Relase/Techgamr.Utils.General.1.0.0.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "github" --no-symbols true
